# version: '3'

# services:
#   django:
#     image: django
#     container_name: ${DATABASE_CONTAINER_NAME}
#     environment:
#       POSTGRES_USER: ${DATABASE_USER}
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#       POSTGRES_DB: ${DATABASE_NAME}
#     env_file:
#       - .env
#     ports:
#       - "${DATABASE_PORT}:5432"
#       # - "5432:5432"
#     volumes:
#       - ./data:/var/lib/postgresql/data

#   telegram_bot:
#     container_name: ${TELEGRAM_BOT_CONTAINER_NAME}
#     build: ${TELEGRAM_BOT_FOLDER}
#     depends_on:
#       - data_base

# volumes:
#   data:

version: "3"

services:
  app:
    build: ./app
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - ./.env:/.env